### ISSUE TITLE
How to evaluate a reward function in gynmasium

### ISSUE THREAD

**Issue by ekomlenovic** [VIRAL-UCBL1/VIRAL#10]
Idea :

- Normalize Reward
$$
R=\frac{R_{i}-R_{\min}}{R_{\max}-R_{\min}} 
$$
- Calculate the std
- with ppo we have some metrics maybe entropy can be good
![image](https://github.com/user-attachments/assets/bde43b2a-6054-40ad-8f5f-b38f02f50142)
How to determine failure and success ? 
- + frequency of failure 
- + frequency of sucess
- +  ratio

started implementation in c8f1cbeb9caa8c54fe9a7b68019d4b1a3d517c90 but it doesn't work properly at this time

**Comment by valentincuzin** [comment]
finish i hope, using norm for reward during train, and std
